### ISSUE TITLE
PHP error Call to a member function setTimezone() on bool

### ISSUE THREAD

**Issue by jamesmacwhite** [barrelstrength/craft-sprout-base-reports#15]
### Description

```
Error: Call to a member function setTimezone() on bool in /app/vendor/barrelstrength/sprout-base-reports/src/services/Reports.php:185
Stack trace:
#0 /app/vendor/barrelstrength/sprout-base-reports/src/elements/Report.php(529): barrelstrength\sproutbasereports\services\Reports->getUtcDateTime(Array)
#1 /app/vendor/barrelstrength/sprout-forms/src/integrations/sproutreports/datasources/EntriesDataSource.php(86): barrelstrength\sproutbasereports\elements\Report->getStartEndDate()
#2 /app/vendor/barrelstrength/sprout-base-reports/src/controllers/ReportsController.php(160): barrelstrength\sproutforms\integrations\sproutreports\datasources\EntriesDataSource->getResults(Object(barrelstrength\sproutbasereports\elements\Report))
#3 [internal function]: barrelstrength\sproutbasereports\controllers\ReportsController->actionResultsIndexTemplate(Object(barrelstrength\sproutbasereports\elements\Report), 294240)
#4 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /app/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#6 /app/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('results-index-t...', Array)
#7 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('results-index-t...', Array)
#8 /app/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('sprout-base-rep...', Array)
#9 /app/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('sprout-base-rep...', Array)
#10 /app/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#11 /app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#12 /app/web/index.php(23): yii\base\Application->run()
#13 {main}
```

### Steps to reproduce

Export a Sprout Forms report from the Craft Admin CP.

### Additional info

- Craft version: 3.5.19
- PHP version: PHP 7.4
- Database driver & version:  MySQL 8

**Comment by jamesmacwhite** [comment]
This seems to be triggered based on certain environment conditions or parameters. It happens on my dev using Craft CMS docker images, but not on our staging environment

**Comment by jamesmacwhite** [comment]
I think I know what's going on, I'm not putting a start or end date deliberately as I want to get all records with any date limiting criteria, however it appears this might be an issue, although start and end date isn't a forced field.
